FROM python:3.9

WORKDIR /app

RUN pip config --user set global.progress_bar off
RUN pip install Cython
RUN pip install flask
RUN pip install flask-cors
RUN pip install waitress
RUN pip install urlextract
RUN pip install ctranslate2
RUN pip install sacremoses
RUN pip install sentence_splitter
RUN pip install youtokentome

COPY models /app/models
COPY nonbreaking_prefixes /app/nonbreaking_prefixes

COPY CTranslator.py /app/

# CMD ["flask", "--app=CTranslator", "run", "--host=0.0.0.0", "--port=5000"]
CMD ["python", "CTranslator.py"]
