#!/bin/bash
#echo __ sm_translate_de-hsb.sh $0 $1 $2 $3 $4 $5 >~/tmp.txt

SRC_LANG=de
DST_LANG=hsb

FILE_SRC=$1
FILE_SRC_SENTENCE_OUTPUT=$2
FILE_SRC_MOSES=$3
FILE_DST_TRANSLATION_RAW=$4
FILE_DST_SENTENCE_RESULT=$5

${MT_SCRIPTS}/sm_translate.sh $SRC_LANG $DST_LANG $FILE_SRC $FILE_SRC_SENTENCE_OUTPUT $FILE_SRC_MOSES $FILE_DST_TRANSLATION_RAW $FILE_DST_SENTENCE_RESULT
