FROM python:3.9.7

# docker build -f Dockerfile.libretranslate -t sotra_libretranslate .

WORKDIR /app

RUN pip config --user set global.progress_bar off
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY sentence_splitter/non_breaking_prefixes /app/sentence_splitter/non_breaking_prefixes

COPY libretranslate_compatible_server.py .
COPY inference_new2.py .

RUN mkdir models1/
COPY models1 models1/

CMD ["python3", "libretranslate_compatible_server.py"]
